config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('place.urls')),
    path('accounts/', include('accounts.urls')),
]

place/urls.py
from django.urls import path
from .views import search_view, detail_view, PlaceLike, PlaceFavorite, PlaceFavoriteList, PlaceLikeList

app_name = 'place'

urlpatterns = [
    path('detail/<int:place_id>/', detail_view, name='detail'),
    path('like/<int:place_id>/', PlaceLike.as_view(), name ='like'),
    path('favorite/<int:place_id>/', PlaceFavorite.as_view(), name='favorite'),
    path("like/", PlaceLikeList.as_view(), name="like_list"),
    path("favorite/", PlaceFavoriteList.as_view(), name="favorite_list"),
    path('', search_view, name='search'),
]

place/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User
import requests


class Category(models.Model):
    name = models.CharField(max_length=30)


class Area(models.Model):
    name = models.CharField(max_length=10)


class Place(models.Model):
    area = models.ManyToManyField(Area, related_name='places')
    name = models.CharField(max_length=30)
    url = models.URLField()
    image_url = models.URLField(null=True)
    address = models.CharField(max_length=50, null=True)
    phone = models.CharField(max_length=20, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True, related_name='places')
    detail_category = models.CharField(max_length=30, null=True)
    price = models.CharField(max_length=30, null=True)
    car = models.CharField(max_length=20, null=True)
    opening_hour = models.CharField(max_length=20, null=True)

    like = models.ManyToManyField(User, related_name='like_post', blank=True)
    favorite = models.ManyToManyField(User, related_name='favorite_post', blank=True)

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if self.detail_category in ('카페 / 디저트', '베이커리'):
            self.category = Category.objects.get(name='후식')

        elif self.detail_category in ('일반 주점', '치킨 / 호프 / 펍', '칵테일 / 와인', '전통 주점 / 포차', '이자카야 / 오뎅 / 꼬치'):
            self.category = Category.objects.get(name='술')

        else:
            self.category = Category.objects.get(name='밥')

        return super().save(force_insert=False, force_update=False, using=None, update_fields=None)

    def get_absolute_url(self):
        return reverse('place:detail', args=[self.id])

    def address_to_location(self):

        url = "https://naveropenapi.apigw.ntruss.com/map-geocode/v2/geocode?query="+self.address+"&coordinate=11,10"
        custom_headers = {
            "X-NCP-APIGW-API-KEY-ID" : 'utkqk0r5dp',
            "X-NCP-APIGW-API-KEY" : "oc9RIxevNLeRbwhMECDKOqlt5EAdRPqi5BpdW4rE"
        }
        req=requests.get(url, headers=custom_headers)
        try:
            return (req.json()["addresses"][0]["x"], req.json()["addresses"][0]["y"])
        except:
            print(self.address, '좌표화 불가')
            return None

place/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Area, Place
from bs4 import BeautifulSoup
from django.db.models import Q
import random
import requests
from django.views.generic.base import View
from django.http import HttpResponseForbidden, HttpResponseRedirect
from urllib.parse import urlparse
from django.views.generic.list import ListView
from django.contrib import messages


CUSTOM_HEADER = {
    'referer': 'https://www.naver.com',
    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/'
                  '537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36'
}
def search_place_list(search_key):
    area = Area.objects.create(name=search_key.strip())
    for i in range(1, 5):
        page_url = "https://www.mangoplate.com/search/?keyword="+str(search_key)+"&page="+str(i)
        page_request = requests.get(page_url, headers=CUSTOM_HEADER)
        soup = BeautifulSoup(page_request.text, "html.parser")
        places = soup.select("figure.restaurant-item ")
        for place in places:
            place_img_url = place.select_one("img").get('data-original')
            if place_img_url is None:
                continue
            place_url = "https://www.mangoplate.com" + place.select_one(".info a").get('href')
            place_request = requests.get(place_url, headers=CUSTOM_HEADER)
            place_soup = BeautifulSoup(place_request.text, "html.parser")
            place_name = place_soup.select_one('h1.restaurant_name').text
            place_info = place_soup.select('table.info tr')

            place_dict = dict()
            for tr in place_info:
                place_dict[tr.select_one('th').text.replace('\n', '').strip()] = tr.select_one('td').text.replace('\n', '')

            place_address = place_dict.get('주소')
            place_phone = place_dict.get('전화번호')
            place_detail_category = place_dict.get('음식 종류')
            place_price = place_dict.get('가격대')
            if place_price is None:
                place_price = '만원-2만원'
            place_car = place_dict.get('주차')
            place_opening_hour = place_dict.get('영업시간')

            place_obj = Place.objects.create(name=place_name,
                                             url=place_url,
                                             image_url=place_img_url,
                                             address=place_address,
                                             phone=place_phone,
                                             detail_category=place_detail_category,
                                             price=place_price,
                                             car=place_car,
                                             opening_hour=place_opening_hour)
            place_obj.area.add(area)
            place_obj.save()


def search_view(request):
    if request.method == 'GET':
        return render(request, 'place/search_view.html')

    food_type = request.POST.getlist('food_type', '밥')
    bob_Q = Q(category_id=3) if '밥' in food_type else Q()
    sool_Q = Q(category_id=1) if '술' in food_type else Q()
    desert_Q = Q(category_id=2) if '후식' in food_type else Q()

    money_type = request.POST.getlist('money_type', '만원')
    money1_Q = Q(price='만원 미만') if '만원' in money_type else Q()
    money2_Q = Q(price='만원-2만원') if '2만원' in money_type else Q()
    money3_Q = Q(price='2만원-3만원') if '2만원이상' in money_type else Q()
    search_key = request.POST.get('search_key'.strip())

    area_filter = Area.objects.filter(name=search_key)

    if area_filter.exists():
        place_filter = area_filter[0].places.filter((bob_Q| sool_Q| desert_Q) & (money1_Q| money2_Q| money3_Q))
    else:
        search_place_list(search_key)
        place_filter = Area.objects.get(name=search_key).places.filter((bob_Q| sool_Q| desert_Q) & (money1_Q| money2_Q| money3_Q))
    place_count = place_filter.count()
    random_index = random.randint(0, place_count-1)
    random_place = place_filter[random_index]
    return redirect(random_place)



def detail_view(request, place_id):
    object = get_object_or_404(Place, pk=place_id)
    location_x, location_y = object.address_to_location()
    return render(request, 'place/detail_view.html', {'object': object,
                                                      'location_x': location_x,
                                                      'location_y': location_y})


class PlaceLike(View):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:    #로그인확인
            return HttpResponseForbidden()
        else:
            if 'place_id' in kwargs:
                place_id = kwargs['place_id']
                place = Place.objects.get(pk=place_id)
                user = request.user
                if user in place.like.all():
                    place.like.remove(user)
                else:
                    place.like.add(user)
            referer_url = request.META.get('HTTP_REFERER')
            path = urlparse(referer_url).path
            return HttpResponseRedirect(path)


class PlaceFavorite(View):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:    #로그인확인
            return HttpResponseForbidden()
        else:
            if 'place_id' in kwargs:
                place_id = kwargs['place_id']
                place = Place.objects.get(pk=place_id)
                user = request.user
                if user in place.favorite.all():
                    place.favorite.remove(user)
                else:
                    place.favorite.add(user)
            referer_url = request.META.get('HTTP_REFERER')
            path = urlparse(referer_url).path
            return HttpResponseRedirect(path)


class PlaceLikeList(ListView):
    model = Place
    template_name = 'place/place_likelist.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:  # 로그인확인
            messages.warning(request, '로그인을 먼저하세요')
            return HttpResponseRedirect('/')
        return super(PlaceLikeList, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        # 내가 좋아요한 글을 보여주
        user = self.request.user
        queryset = user.like_post.all()
        return queryset


class PlaceFavoriteList(ListView):
    model = Place
    template_name = 'place/place_favoritelist.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:  # 로그인확인
            messages.warning(request, '로그인을 먼저하세요')
            return HttpResponseRedirect('/')
        return super(PlaceFavoriteList, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        # 내가 좋아요한 글을 보여주기
        user = self.request.user
        queryset = user.favorite_post.all()
        return queryset

place/templates/place/detail_view.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}
{% load static %}
{% block content %}
<script type="text/javascript" src="https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=utkqk0r5dp&amp;submodules=panorama"></script>
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-4 col-md-4">
        <div class="card" style="">
            <img src=" {{ object.image_url }}" class="card-img-top" alt="...">
            <div class="card-body">

                <h5 class="card-title">{{ object.name }}</h5>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">{{ object.address }}</li>
                <li class="list-group-item">{{ object.phone }}</li>
                <li class="list-group-item">{{ object.detail_category }}</li>
                <li class="list-group-item">{{ object.price }}</li>
                <li class="list-group-item">{{ object.car }}</li>
                <li class="list-group-item">{{ object.opening_hour }}</li>
                <li class="list-group-item">
                        <a href="{% url 'place:like' object.id %}" class="float-left btn-like {%if user in object.like.all %}active{%endif%}">좋아요!</a>
                        {% if object.like.all.count %}
                        <span class = "float-left">
                            {{object.like.all.count}}
                        </span>
                        {% endif %}
                        <a href="{% url 'place:favorite' object.id %}" class="float-right btn-favorite {%if user in object.favorite.all %}active{%endif%}">저장하기!</a>
                    </li>
                <li class="list-group-item">
                    {% load disqus_tags %}
                    <div class="card-body">
                        {% disqus_show_comments %}
                    </div>
                </li>
            </ul>
        </div>
    </div>
    <div class="col">
        <div id="map" style="width:300px;height:300px;"></div>
    </div>
</div>
<script>
var map = new naver.maps.Map('map', {
    center: new naver.maps.LatLng({{location_y}}, {{location_x}}),
    zoom: 10
});

var marker = new naver.maps.Marker({
    position: new naver.maps.LatLng({{location_y}}, {{location_x}}),
    map: map
});
</script>
{% endblock %}

place/templates/place/place_detail.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-6 col-md-4">
        <div class="card" style="">
            <img src=" {{ object.image_url }}" class="card-img-top" alt="...">
            <div class="card-body">

                <h5 class="card-title">{{ object.name }}</h5>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">{{ object.address }}</li>
                <li class="list-group-item">{{ object.phone }}</li>
                <li class="list-group-item">{{ object.detail_category }}</li>
                <li class="list-group-item">{{ object.price }}</li>
                <li class="list-group-item">{{ object.car }}</li>
                <li class="list-group-item">{{ object.opening_hour }}</li>
                <li class="list-group-item">
                        <a href="{% url 'place:like' object.id %}" class="float-left btn-like {%if user in object.like.all %} active {%endif%}">좋아요!</a>
                        {% if object.like.all.count %}
                        <span class = "float-left">
                            {{object.like.all.count}}
                        </span>
                        {% endif %}
                        <a href="{% url 'place:favorite' object.id %}" class="float-right btn-favorite {%if user in object.favorite.all %} active {%endif%}">저장하기!</a>
                    </li>
                <li class="list-group-item">

                    {% load disqus_tags %}
                    <div class="card-body">
                        {% disqus_show_comments %}
                    </div>
                </li>
            </ul>
        </div>
    </div>

    <div class="col"></div>
</div>
{% endblock %}

place/templates/place/search_view.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Random Plate{% endblock %}
{% block content %}
<div class="pg-main">
    <header class="main-header" style="background-image: url('{% static 'images/main_top.jpg' %}');">
        <p class="title">골라 주는대로 먹어라!</p>
        <h1 class="title">랜덤 플레이트!</h1>
        <br />
        <br />
        <br />
        <br />
    </header>
</div>

<br />
<br />


<form action="" method="post" id="search_form">
    {%csrf_token%}

    <div class="container h-100">
        <div class="d-flex justify-content-center h-100">
            <div class="searchbar">
                <input class="search_input" type="text" name="search_key" style="color:#ff0000; font-weight:bold;" placeholder="어디로 갈까?">
                <button type="submit" class="search_icon"><i class="fas fa-search"></i></button>
                <!--          <a href="#" class="search_icon"><i class="fas fa-search"></i></a>-->
            </div>
        </div>
    </div>
    <br />
    <br />

    <div>
        <div class="templates-wrapper">
            <div class="templates-scrollbar" style="position: relative; overflow: hidden; width: 100%; height: 100%;">
                <div style="position: absolute; top: 0px; left: 0px; right: 0px; bottom: 0px; overflow: scroll; margin-right: -15px; margin-bottom: -15px;">
                    <div class="list-templates">
                        <div class="templates-strip">
                            <div class="template">
                            <span class="template-preview color-a">
                                <span class="image">
                                    <span class="form-row align-items-center justify-content-center">
                                        <span class="form-check form-check-inline">
                                            <input class="form-check-input" type="checkbox" id="inlineCheckbox1" value="밥" name="food_type">
                                            <label class="form-check-label" style="padding:25px 25px 25px 25px; color:white;"for="inlineCheckbox1">밥</label>
                                        </span>
                                    </span>
                                </span>
                            </span>
                                <span class="title"></span>
                            </div>
                            <div class="template">
                            <span class="template-preview color-b">
                                <span class="image">
                                    <span class="form-row align-items-center justify-content-center">
                                        <span class="form-check form-check-inline">
                                            <input class="form-check-input" type="checkbox" id="inlineCheckbox2" value="술" name="food_type">
                                            <label class="form-check-label" style="padding:25px 25px 25px 25px;" for="inlineCheckbox2">술</label>
                                        </span>
                                    </span>
                                </span>
                            </span>
                            </div>
                            <div class="template">
                            <span class="template-preview color-c">
                                <span class="image">
                                    <span class="image">
                                        <span class="form-row align-items-center justify-content-center">
                                            <span class="form-check form-check-inline">
                                                <input class="form-check-input" type="checkbox" id="inlineCheckbox3" value="후식" name="food_type">
                                                <label class="form-check-label" style="padding:25px 25px 25px 25px;" for="inlineCheckbox3">후식</label>
                                            </span>
                                        </span>
                                    </span>
                                </span>
                            </span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div>
            <div class="templates-wrapper">
                <div class="templates-scrollbar" style="position: relative; overflow: hidden; width: 100%; height: 100%;">
                    <div style="position: absolute; top: 0px; left: 0px; right: 0px; bottom: 0px; overflow: scroll; margin-right: -15px; margin-bottom: -15px;">
                        <div class="list-templates">
                            <div class="templates-strip">
                                <div class="template" style="width: 180px;">
                            <span class="template-preview color-d">
                                <span class="image">
                                    <span class="form-row align-items-center justify-content-center">
                                        <span class="form-check form-check-inline">
                                            <input class="form-check-input" type="checkbox" id="inlineCheckbox4" value="만원" name="money_type">
                                            <label class="form-check-label" style="padding:25px 10px 25px 10px;" for="inlineCheckbox4">만원</label>
                                        </span>
                                    </span>
                                </span>
                            </span>
                                    <span class="title"></span>
                                </div>
                                <div class="template" style="width: 180px;">
                            <span class="template-preview color-e">
                                <span class="image">
                                    <span class="form-row align-items-center justify-content-center">
                                        <span class="form-check form-check-inline">
                                            <input class="form-check-input" type="checkbox" id="inlineCheckbox5" value="2만원" name="money_type">
                                            <label class="form-check-label" style="padding:25px 10px 25px 10px;" for="inlineCheckbox5">2만원이하</label>
                                        </span>
                                    </span>
                                </span>
                            </span>
                                </div>
                                <div class="template" style="width: 180px;">
                            <span class="template-preview color-f">
                                <span class="image">
                                    <span class="image">
                                        <span class="form-row align-items-center justify-content-center">
                                            <span class="form-check form-check-inline">
                                                <input class="form-check-input" type="checkbox" id="inlineCheckbox6" value="2만원이상" name="money_type">
                                                <label class="form-check-label" style="padding:25px 10px 25px 10px;" for="inlineCheckbox6">2만원이상</label>
                                            </span>
                                        </span>
                                    </span>
                                </span>
                            </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}