accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import signup

app_name = "accounts"

urlpatterns = [
    path('signup/', signup, name ='signup'),
    path('login/', LoginView.as_view(template_name = 'accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name = 'accounts/logout.html'), name='logout'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('place.urls')),
    path('accounts/', include('accounts.urls')),
]

place/urls.py
from django.urls import path
from .views import search_view, detail_view, PlaceLike, PlaceFavorite, PlaceFavoriteList, PlaceLikeList

app_name = 'place'

urlpatterns = [
    path('detail/<int:place_id>/', detail_view, name='detail'),
    path('like/<int:place_id>/', PlaceLike.as_view(), name ='like'),
    path('favorite/<int:place_id>/', PlaceFavorite.as_view(), name='favorite'),
    path("like/", PlaceLikeList.as_view(), name="like_list"),
    path("favorite/", PlaceFavoriteList.as_view(), name="favorite_list"),
    path('', search_view, name='search'),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.models import User
from django import forms


class SignUpForm(forms.ModelForm):

    password = forms.CharField(label = 'Password', widget=forms.PasswordInput)
    Repeat_password = forms.CharField(label='Repeat_password', widget=forms.PasswordInput)

    class Meta:
        model = User
        # fields에는 해당 모델에 대해 입력 받을 필드들을 나열한다.
        # + 추가 필드도 포함 될 수 있다.
        fields = [ 'username', 'password', 'Repeat_password', ]



    def clean_Repeat_password(self):
        cd = self.cleaned_data
        if cd['password'] != cd['Repeat_password']:
            raise forms.ValidationError('비밀번호가 일치하지 않습니다.')
        return cd['Repeat_password']

accounts/views.py
from django.shortcuts import render

from django.http import HttpResponseForbidden
from django.shortcuts import render
from django.contrib.auth.models import User
from .forms import SignUpForm



def signup(request):
    if request.method == 'POST':
        signup_form = SignUpForm(request.POST)
        print("hi")
        if signup_form.is_valid():
            user_instance = signup_form.save(commit=False)
            user_instance.set_password(signup_form.cleaned_data['password'])
            user_instance.save()

            return render(request, 'accounts/signup_complete.html', {'username':user_instance.username})

    else:
        signup_form = SignUpForm()

    return render(request, 'accounts/signup.html', {'form':signup_form})

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="'col-6">
        <div class="alert alert-primary" role="alert">
            Please enter your login information. </div>
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="login" class = 'btn btn-outline-primary'>
        </form>
    </div>
    <div class="col"></div>

</div>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block title %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="'col-6">
        <div class="alert alert-primary" role="alert">
            로그아웃이 잘 되었습니다. </div>
        <a href="{% url 'accounts:login'%}" class="btn btn-outline-success">login 하기</a>
    </div>
    <div class="col"></div>

</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}

<div class = row>
    <div class = "col"></div>
    <div class = "col-6">
        <form action="" method="post">
            <div class = "alert alert-info">Please enter your account information</div>
                {% csrf_token %}
            {{ form.as_p }}
        <input type="submit" value="Sign up" class="btn btn-outline-info">
        </form>
    </div>
    <div class = 'col'></div>


</div>

{% endblock %}

accounts/templates/accounts/signup_complete.html
{% extends 'base.html' %}

{% block title %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="'col-6">
        <div class="alert alert-primary" role="alert">
            {{ username }} are succesfully signed.up </div>
        <a href="{% url 'accounts:login' %}">Move to login</a>
    </div>
    <div class="col"></div>

</div>
{% endblock %}